version: 0.1
log:
  level: info 
storage:
  filesystem:
    rootdirectory: /var/lib/registry
    maxthreads: 100
http:
    addr: 0.0.0.0:5000
    secret: placeholder
    tls:
      certificate: /etc/registry/ssl/offlineregistry.offline-k8s.com.crt
      key: /etc/registry/ssl/offlineregistry.offline-k8s.com.key
